Add cryptography as a requirement to prevent pymysql RuntimeError
In site-packages/pymysql/_auth.py the following is raised when trying to
connect:

RuntimeError: 'cryptography' package is required for sha256_password or
caching_sha2_password auth methods